name: Gerar Token Tray
on: [workflow_dispatch]

jobs:
  gerar_token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar Biblioteca
        run: pip install requests
      - name: Executar Script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          CODE_TRAY: ${{ secrets.CODE_TRAY }}
          REFRESH_TOKEN_TRAY: ${{ secrets.REFRESH_TOKEN_TRAY }}
          ACCESS_TOKEN_TRAY: ${{ secrets.ACCESS_TOKEN_TRAY }}
        run: python lista_produtos.py
